# Generated by Django 2.2.5 on 2019-10-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('a', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
