# Generated by Django 2.2.5 on 2019-10-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tousu',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('num', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
