# Generated by Django 2.2.5 on 2019-10-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tousu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
