# Generated by Django 2.2.5 on 2019-10-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191021_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
