# Generated by Django 2.2.5 on 2019-10-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
