# Generated by Django 2.2.5 on 2019-10-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20191022_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pic',
        ),
    ]
